### ISSUE TITLE
Do you know how to set timeout for every step?

### ISSUE THREAD

**Issue by ChrisD1990** [jbehave/jbehave-tutorial#17]
i have a problem, my test scenario have more than 30 steps, and One step took more than 30 minutes to execute shell script on linux server, However, if the step exceeds 30 minutes, it will timeout and terminate the test scenario. Do you know how to set the step timeout?

**Comment by maurotalevi** [comment]
This feature is not implemented.   In the future, please refer to  
https://jbehave.org/how-to-contribute.html

**Comment by ChrisD1990** [comment]
ok, thanks for your replay @maurotalevi
