### ISSUE TITLE
Why JBehave AfterScenario is not picking the tag value

### ISSUE THREAD

**Issue by CrazyMunda** [jbehave/jbehave-tutorial#22]
Hi All,
I am trying to write some specific step based on given tags for scenario . But my After scenario is not picking the tags and i am not sure what i am missing here. I am using **Serenity and JBehave**
in my story file i am using
**META:@test test**
and in my step definitions i am using
`@AfterScenario public void AfterScenario( @ Named("test") String Testname) // **but testname is always coming empty { { } }`**
Am I missing anything here.

 Thanks for the help.

**Comment by paul-hammant** [comment]
Any chance you could make a fully reproducible example (GitHub repo, maven pom.xml file, runnable etc) ?

**Comment by CrazyMunda** [comment]
Actually nothing much is there in the project story file contain.

> Meta:@Tag Value

Narrative:
As a user 

Scenario: As a user I shall be able to able to perform following operation
@positive
@test_
@scencrsLM_
@component_
@AdvancedSearch
@testtype_BDD-Auto
Given I Launched the browser
When  browser is up
Then I closed the browser

And then i have after scenario in step File
`@BeforeStories
    public void BeforeStories(@Named("Tag") String tag)
    {
        String str ="hello";
        if(str!=null)
        {

        }
    }`

That's pretty much , but i am not sure why i am not getting tag value here . It does come once but no idea after that no code change nothing.

Thanks

**Comment by paul-hammant** [comment]
Make a repo please. Fully reproducible.

**Comment by CrazyMunda** [comment]
I was able to solve the issue . thanks for the help
